const GET_MOVIES = "GET_MOVIES";
const SET_ERROR = "SET_ERROR";
const SET_LOADING = "SET_LOADING";
const SET_PARAMS = "SET_PARAMS";
const CLEAR_PARAMS = "CLEAR_PARAMS";
const REMOVE_PARAMS = "REMOVE_PARAMS";
const TOGGLED_SIDE = "TOGGLED_SIDE";
const FILTER_MOVIES = "FILTER_MOVIES";
const SET_WATCHLIST = "SET_WATCHLIST";
const REMOVE_WATCHLIST = "REMOVE_WATCHLIST";

export {
  GET_MOVIES,
  SET_ERROR,
  TOGGLED_SIDE,
  SET_LOADING,
  FILTER_MOVIES,
  SET_PARAMS,
  REMOVE_PARAMS,
  CLEAR_PARAMS,
  SET_WATCHLIST,
  REMOVE_WATCHLIST,
};
