const GET_MOVIES = "GET_MOVIES";
const SET_ERROR = "SET_ERROR";
const SET_LOADING = "SET_LOADING";
const TOGGLED_SIDE = "TOGGLED_SIDE";
const FILTER_MOVIES = "FILTER_MOVIES";

export { GET_MOVIES, SET_ERROR, TOGGLED_SIDE, SET_LOADING, FILTER_MOVIES };
